available_text_models: ["gpt-4o-mini", "gpt-4o","gpt-4"]
info:
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is our most advanced multimodal model that’s <b>faster</b> and <b>cheaper</b> than GPT-4. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.0025
    price_per_1000_output_tokens: 0.00125

    scores:
      Smart: 4
      Fast: 2
      Cheap: 4
  gpt-4o-mini:
    type: chat_completion
    name: GPT-4o-mini
    description: GPT-4o mini is our most cost-efficient small model that’s <b>smarter</b> and <b>cheaper</b> than GPT-3.5 Turbo. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.00015
    price_per_1000_output_tokens: 0.000075

    scores:
      Smart: 2
      Fast: 2
      Cheap: 5
  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 is the <b>smartest</b> and most advanced model in the world. But it is slower and not as cost-efficient as ChatGPT. Best choice for <b>complex</b> intellectual tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2
  

